# Generated by Django 4.1.3 on 2022-11-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BiblicalVerse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verse_title", models.CharField(max_length=20)),
                ("verse_txt", models.TextField()),
            ],
        ),
        migrations.AddConstraint(
            model_name="biblicalverse",
            constraint=models.UniqueConstraint(
                fields=("verse_title",), name="unique_verse"
            ),
        ),
    ]
